/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateFolderArgs { 'icon' : string, 'name' : string }
export interface CreateScanArgs {
  'scanType' : ScanType,
  'tags' : Array<string>,
  'extractedText' : string,
  'confidenceScore' : number,
  'language' : string,
  'image' : ExternalBlob,
  'folderId' : [] | [FolderId],
}
export type ExternalBlob = Uint8Array;
export type FolderId = string;
export interface FolderView {
  'id' : FolderId,
  'userId' : UserId,
  'icon' : string,
  'name' : string,
  'createdAt' : Timestamp,
}
export interface ListScansArgs {
  'includeDeleted' : boolean,
  'offset' : bigint,
  'limit' : bigint,
  'folderId' : [] | [FolderId],
}
export interface ListScansResult { 'total' : bigint, 'scans' : Array<ScanView> }
export type ScanId = string;
export type ScanType = { 'receipt' : null } |
  { 'other' : null } |
  { 'card' : null } |
  { 'document' : null };
export interface ScanView {
  'id' : ScanId,
  'isDeleted' : boolean,
  'scanType' : ScanType,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'isFavorite' : boolean,
  'extractedText' : string,
  'confidenceScore' : number,
  'language' : string,
  'updatedAt' : Timestamp,
  'image' : ExternalBlob,
  'exportCount' : bigint,
  'folderId' : [] | [FolderId],
  'isPinned' : boolean,
}
export type SubscriptionId = string;
export interface SubscriptionView {
  'id' : SubscriptionId,
  'stripeSubscriptionId' : [] | [string],
  'userId' : UserId,
  'plan' : string,
  'currentPeriodEnd' : [] | [Timestamp],
}
export type Timestamp = bigint;
export interface UpdateScanArgs {
  'id' : ScanId,
  'tags' : [] | [Array<string>],
  'isFavorite' : [] | [boolean],
  'extractedText' : [] | [string],
  'confidenceScore' : [] | [number],
  'language' : [] | [string],
  'exportCount' : [] | [bigint],
  'folderId' : [] | [FolderId],
  'isPinned' : [] | [boolean],
}
export interface UpdateUserArgs {
  'plan' : [] | [UserPlan],
  'language' : [] | [string],
}
export interface UpsertSubscriptionArgs {
  'stripeSubscriptionId' : [] | [string],
  'plan' : string,
  'currentPeriodEnd' : [] | [Timestamp],
}
export interface UsageLimitsView {
  'scansToday' : bigint,
  'userId' : UserId,
  'canScan' : boolean,
  'dailyLimit' : bigint,
  'lastResetDate' : Timestamp,
}
export type UserId = Principal;
export type UserPlan = { 'premium' : null } |
  { 'free' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserView {
  'id' : UserId,
  'scansToday' : bigint,
  'createdAt' : Timestamp,
  'plan' : UserPlan,
  'language' : string,
  'totalScans' : bigint,
  'updatedAt' : Timestamp,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkUsageLimit' : ActorMethod<[], UsageLimitsView>,
  'createFolder' : ActorMethod<[CreateFolderArgs], FolderView>,
  'createOrUpdateSubscription' : ActorMethod<
    [UpsertSubscriptionArgs],
    SubscriptionView
  >,
  'createScan' : ActorMethod<[CreateScanArgs], ScanView>,
  'deleteAccount' : ActorMethod<[], undefined>,
  'deleteFolder' : ActorMethod<[FolderId], undefined>,
  'deleteScan' : ActorMethod<[ScanId], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrCreateUser' : ActorMethod<[], UserView>,
  'getScan' : ActorMethod<[ScanId], [] | [ScanView]>,
  'getSubscription' : ActorMethod<[], [] | [SubscriptionView]>,
  'incrementScanCount' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listFolders' : ActorMethod<[], Array<FolderView>>,
  'listScans' : ActorMethod<[ListScansArgs], ListScansResult>,
  'resetDailyLimits' : ActorMethod<[], undefined>,
  'restoreScan' : ActorMethod<[ScanId], undefined>,
  'searchScans' : ActorMethod<[string], Array<ScanView>>,
  'updateScan' : ActorMethod<[UpdateScanArgs], ScanView>,
  'updateUser' : ActorMethod<[UpdateUserArgs], UserView>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];