/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const UsageLimitsView = IDL.Record({
  'scansToday' : IDL.Int,
  'userId' : UserId,
  'canScan' : IDL.Bool,
  'dailyLimit' : IDL.Int,
  'lastResetDate' : Timestamp,
});
export const CreateFolderArgs = IDL.Record({
  'icon' : IDL.Text,
  'name' : IDL.Text,
});
export const FolderId = IDL.Text;
export const FolderView = IDL.Record({
  'id' : FolderId,
  'userId' : UserId,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
});
export const UpsertSubscriptionArgs = IDL.Record({
  'stripeSubscriptionId' : IDL.Opt(IDL.Text),
  'plan' : IDL.Text,
  'currentPeriodEnd' : IDL.Opt(Timestamp),
});
export const SubscriptionId = IDL.Text;
export const SubscriptionView = IDL.Record({
  'id' : SubscriptionId,
  'stripeSubscriptionId' : IDL.Opt(IDL.Text),
  'userId' : UserId,
  'plan' : IDL.Text,
  'currentPeriodEnd' : IDL.Opt(Timestamp),
});
export const ScanType = IDL.Variant({
  'receipt' : IDL.Null,
  'other' : IDL.Null,
  'card' : IDL.Null,
  'document' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreateScanArgs = IDL.Record({
  'scanType' : ScanType,
  'tags' : IDL.Vec(IDL.Text),
  'extractedText' : IDL.Text,
  'confidenceScore' : IDL.Float64,
  'language' : IDL.Text,
  'image' : ExternalBlob,
  'folderId' : IDL.Opt(FolderId),
});
export const ScanId = IDL.Text;
export const ScanView = IDL.Record({
  'id' : ScanId,
  'isDeleted' : IDL.Bool,
  'scanType' : ScanType,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'isFavorite' : IDL.Bool,
  'extractedText' : IDL.Text,
  'confidenceScore' : IDL.Float64,
  'language' : IDL.Text,
  'updatedAt' : Timestamp,
  'image' : ExternalBlob,
  'exportCount' : IDL.Int,
  'folderId' : IDL.Opt(FolderId),
  'isPinned' : IDL.Bool,
});
export const UserPlan = IDL.Variant({
  'premium' : IDL.Null,
  'free' : IDL.Null,
});
export const UserView = IDL.Record({
  'id' : UserId,
  'scansToday' : IDL.Int,
  'createdAt' : Timestamp,
  'plan' : UserPlan,
  'language' : IDL.Text,
  'totalScans' : IDL.Int,
  'updatedAt' : Timestamp,
});
export const ListScansArgs = IDL.Record({
  'includeDeleted' : IDL.Bool,
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
  'folderId' : IDL.Opt(FolderId),
});
export const ListScansResult = IDL.Record({
  'total' : IDL.Nat,
  'scans' : IDL.Vec(ScanView),
});
export const UpdateScanArgs = IDL.Record({
  'id' : ScanId,
  'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
  'isFavorite' : IDL.Opt(IDL.Bool),
  'extractedText' : IDL.Opt(IDL.Text),
  'confidenceScore' : IDL.Opt(IDL.Float64),
  'language' : IDL.Opt(IDL.Text),
  'exportCount' : IDL.Opt(IDL.Int),
  'folderId' : IDL.Opt(FolderId),
  'isPinned' : IDL.Opt(IDL.Bool),
});
export const UpdateUserArgs = IDL.Record({
  'plan' : IDL.Opt(UserPlan),
  'language' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkUsageLimit' : IDL.Func([], [UsageLimitsView], []),
  'createFolder' : IDL.Func([CreateFolderArgs], [FolderView], []),
  'createOrUpdateSubscription' : IDL.Func(
      [UpsertSubscriptionArgs],
      [SubscriptionView],
      [],
    ),
  'createScan' : IDL.Func([CreateScanArgs], [ScanView], []),
  'deleteAccount' : IDL.Func([], [], []),
  'deleteFolder' : IDL.Func([FolderId], [], []),
  'deleteScan' : IDL.Func([ScanId], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrCreateUser' : IDL.Func([], [UserView], []),
  'getScan' : IDL.Func([ScanId], [IDL.Opt(ScanView)], ['query']),
  'getSubscription' : IDL.Func([], [IDL.Opt(SubscriptionView)], ['query']),
  'incrementScanCount' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listFolders' : IDL.Func([], [IDL.Vec(FolderView)], ['query']),
  'listScans' : IDL.Func([ListScansArgs], [ListScansResult], ['query']),
  'resetDailyLimits' : IDL.Func([], [], []),
  'restoreScan' : IDL.Func([ScanId], [], []),
  'searchScans' : IDL.Func([IDL.Text], [IDL.Vec(ScanView)], ['query']),
  'updateScan' : IDL.Func([UpdateScanArgs], [ScanView], []),
  'updateUser' : IDL.Func([UpdateUserArgs], [UserView], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const UsageLimitsView = IDL.Record({
    'scansToday' : IDL.Int,
    'userId' : UserId,
    'canScan' : IDL.Bool,
    'dailyLimit' : IDL.Int,
    'lastResetDate' : Timestamp,
  });
  const CreateFolderArgs = IDL.Record({ 'icon' : IDL.Text, 'name' : IDL.Text });
  const FolderId = IDL.Text;
  const FolderView = IDL.Record({
    'id' : FolderId,
    'userId' : UserId,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
  });
  const UpsertSubscriptionArgs = IDL.Record({
    'stripeSubscriptionId' : IDL.Opt(IDL.Text),
    'plan' : IDL.Text,
    'currentPeriodEnd' : IDL.Opt(Timestamp),
  });
  const SubscriptionId = IDL.Text;
  const SubscriptionView = IDL.Record({
    'id' : SubscriptionId,
    'stripeSubscriptionId' : IDL.Opt(IDL.Text),
    'userId' : UserId,
    'plan' : IDL.Text,
    'currentPeriodEnd' : IDL.Opt(Timestamp),
  });
  const ScanType = IDL.Variant({
    'receipt' : IDL.Null,
    'other' : IDL.Null,
    'card' : IDL.Null,
    'document' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreateScanArgs = IDL.Record({
    'scanType' : ScanType,
    'tags' : IDL.Vec(IDL.Text),
    'extractedText' : IDL.Text,
    'confidenceScore' : IDL.Float64,
    'language' : IDL.Text,
    'image' : ExternalBlob,
    'folderId' : IDL.Opt(FolderId),
  });
  const ScanId = IDL.Text;
  const ScanView = IDL.Record({
    'id' : ScanId,
    'isDeleted' : IDL.Bool,
    'scanType' : ScanType,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'isFavorite' : IDL.Bool,
    'extractedText' : IDL.Text,
    'confidenceScore' : IDL.Float64,
    'language' : IDL.Text,
    'updatedAt' : Timestamp,
    'image' : ExternalBlob,
    'exportCount' : IDL.Int,
    'folderId' : IDL.Opt(FolderId),
    'isPinned' : IDL.Bool,
  });
  const UserPlan = IDL.Variant({ 'premium' : IDL.Null, 'free' : IDL.Null });
  const UserView = IDL.Record({
    'id' : UserId,
    'scansToday' : IDL.Int,
    'createdAt' : Timestamp,
    'plan' : UserPlan,
    'language' : IDL.Text,
    'totalScans' : IDL.Int,
    'updatedAt' : Timestamp,
  });
  const ListScansArgs = IDL.Record({
    'includeDeleted' : IDL.Bool,
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
    'folderId' : IDL.Opt(FolderId),
  });
  const ListScansResult = IDL.Record({
    'total' : IDL.Nat,
    'scans' : IDL.Vec(ScanView),
  });
  const UpdateScanArgs = IDL.Record({
    'id' : ScanId,
    'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
    'isFavorite' : IDL.Opt(IDL.Bool),
    'extractedText' : IDL.Opt(IDL.Text),
    'confidenceScore' : IDL.Opt(IDL.Float64),
    'language' : IDL.Opt(IDL.Text),
    'exportCount' : IDL.Opt(IDL.Int),
    'folderId' : IDL.Opt(FolderId),
    'isPinned' : IDL.Opt(IDL.Bool),
  });
  const UpdateUserArgs = IDL.Record({
    'plan' : IDL.Opt(UserPlan),
    'language' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkUsageLimit' : IDL.Func([], [UsageLimitsView], []),
    'createFolder' : IDL.Func([CreateFolderArgs], [FolderView], []),
    'createOrUpdateSubscription' : IDL.Func(
        [UpsertSubscriptionArgs],
        [SubscriptionView],
        [],
      ),
    'createScan' : IDL.Func([CreateScanArgs], [ScanView], []),
    'deleteAccount' : IDL.Func([], [], []),
    'deleteFolder' : IDL.Func([FolderId], [], []),
    'deleteScan' : IDL.Func([ScanId], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrCreateUser' : IDL.Func([], [UserView], []),
    'getScan' : IDL.Func([ScanId], [IDL.Opt(ScanView)], ['query']),
    'getSubscription' : IDL.Func([], [IDL.Opt(SubscriptionView)], ['query']),
    'incrementScanCount' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listFolders' : IDL.Func([], [IDL.Vec(FolderView)], ['query']),
    'listScans' : IDL.Func([ListScansArgs], [ListScansResult], ['query']),
    'resetDailyLimits' : IDL.Func([], [], []),
    'restoreScan' : IDL.Func([ScanId], [], []),
    'searchScans' : IDL.Func([IDL.Text], [IDL.Vec(ScanView)], ['query']),
    'updateScan' : IDL.Func([UpdateScanArgs], [ScanView], []),
    'updateUser' : IDL.Func([UpdateUserArgs], [UserView], []),
  });
};

export const init = ({ IDL }) => { return []; };