/**
 * Export service — generate TXT, PDF, CSV, DOCX from OCR text.
 */
import type { ExportFormat } from "@/types";

export interface ExportOptions {
  title?: string;
  watermark?: boolean;
}

/**
 * Export text in the given format and trigger browser download.
 */
export async function exportText(
  text: string,
  format: ExportFormat,
  options: ExportOptions = {},
): Promise<void> {
  const title = options.title ?? "scan";
  const safeTitle = title.replace(/[^a-z0-9]/gi, "_").toLowerCase();

  switch (format) {
    case "txt":
      return exportTxt(text, safeTitle, options);
    case "pdf":
      return exportPdf(text, title, options);
    case "csv":
      return exportCsv(text, safeTitle);
    case "docx":
      return exportDocxPlaceholder(text, safeTitle, options);
  }
}

function exportTxt(text: string, filename: string, opts: ExportOptions): void {
  let content = text;
  if (opts.watermark) content += "\n\n--- Generated by ScanText Pro (Free) ---";
  triggerDownload(content, `${filename}.txt`, "text/plain");
}

function exportPdf(text: string, title: string, opts: ExportOptions): void {
  // Use window.print with a styled iframe for PDF generation
  const watermarkHtml = opts.watermark
    ? `<p style="color:#aaa;font-size:12px;text-align:center;margin-top:40px;">Generated by ScanText Pro (Free)</p>`
    : "";
  const html = `<!DOCTYPE html>
<html><head><title>${title}</title>
<style>
  body { font-family: Arial, sans-serif; padding: 40px; font-size: 14px; line-height: 1.6; }
  pre { white-space: pre-wrap; word-break: break-word; }
</style></head><body>
<h2>${title}</h2>
<pre>${text.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</pre>
${watermarkHtml}
</body></html>`;

  const iframe = document.createElement("iframe");
  iframe.style.display = "none";
  document.body.appendChild(iframe);
  iframe.contentWindow?.document.open();
  iframe.contentWindow?.document.write(html);
  iframe.contentWindow?.document.close();
  setTimeout(() => {
    iframe.contentWindow?.print();
    document.body.removeChild(iframe);
  }, 300);
}

function exportCsv(text: string, filename: string): void {
  // Convert text lines to CSV rows
  const lines = text.split("\n").filter(Boolean);
  const csv = lines.map((l) => `"${l.replace(/"/g, '""')}"`).join("\n");
  triggerDownload(csv, `${filename}.csv`, "text/csv");
}

function exportDocxPlaceholder(
  text: string,
  filename: string,
  opts: ExportOptions,
): void {
  // DOCX export requires a library (docx.js); export as RTF as placeholder
  let content = "{\\rtf1\\ansi\\deff0\n{\\fonttbl{\\f0 Arial;}}\n\\f0\\fs24 ";
  const escaped = text.replace(/\\/g, "\\\\").replace(/\n/g, "\\par\n");
  content += escaped;
  if (opts.watermark)
    content += "\\par\n{\\i Generated by ScanText Pro (Free)}";
  content += "\n}";
  triggerDownload(content, `${filename}.rtf`, "application/rtf");
}

function triggerDownload(
  content: string,
  filename: string,
  mimeType: string,
): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Share text to WhatsApp, email, or native share.
 */
export async function shareText(
  text: string,
  method: "whatsapp" | "email" | "native" | "copy",
  title?: string,
): Promise<void> {
  switch (method) {
    case "whatsapp": {
      const url = `https://wa.me/?text=${encodeURIComponent(text)}`;
      window.open(url, "_blank");
      break;
    }
    case "email": {
      const subject = encodeURIComponent(title ?? "Scanned Text");
      const body = encodeURIComponent(text);
      window.location.href = `mailto:?subject=${subject}&body=${body}`;
      break;
    }
    case "native":
      if (navigator.share) {
        await navigator.share({ title: title ?? "Scanned Text", text });
      }
      break;
    case "copy":
      await navigator.clipboard.writeText(text);
      break;
  }
}
