/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface CreateFolderArgs {
    icon: string;
    name: string;
}
export interface SubscriptionView {
    id: SubscriptionId;
    stripeSubscriptionId?: string;
    userId: UserId;
    plan: string;
    currentPeriodEnd?: Timestamp;
}
export interface UserView {
    id: UserId;
    scansToday: bigint;
    createdAt: Timestamp;
    plan: UserPlan;
    language: string;
    totalScans: bigint;
    updatedAt: Timestamp;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface UsageLimitsView {
    scansToday: bigint;
    userId: UserId;
    canScan: boolean;
    dailyLimit: bigint;
    lastResetDate: Timestamp;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UpdateScanArgs {
    id: ScanId;
    tags?: Array<string>;
    isFavorite?: boolean;
    extractedText?: string;
    confidenceScore?: number;
    language?: string;
    exportCount?: bigint;
    folderId?: FolderId;
    isPinned?: boolean;
}
export interface ListScansArgs {
    includeDeleted: boolean;
    offset: bigint;
    limit: bigint;
    folderId?: FolderId;
}
export interface ScanView {
    id: ScanId;
    isDeleted: boolean;
    scanType: ScanType;
    userId: UserId;
    createdAt: Timestamp;
    tags: Array<string>;
    isFavorite: boolean;
    extractedText: string;
    confidenceScore: number;
    language: string;
    updatedAt: Timestamp;
    image: ExternalBlob;
    exportCount: bigint;
    folderId?: FolderId;
    isPinned: boolean;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type UserId = Principal;
export type SubscriptionId = string;
export interface ListScansResult {
    total: bigint;
    scans: Array<ScanView>;
}
export type ScanId = string;
export interface CreateScanArgs {
    scanType: ScanType;
    tags: Array<string>;
    extractedText: string;
    confidenceScore: number;
    language: string;
    image: ExternalBlob;
    folderId?: FolderId;
}
export interface UpsertSubscriptionArgs {
    stripeSubscriptionId?: string;
    plan: string;
    currentPeriodEnd?: Timestamp;
}
export interface FolderView {
    id: FolderId;
    userId: UserId;
    icon: string;
    name: string;
    createdAt: Timestamp;
}
export interface UpdateUserArgs {
    plan?: UserPlan;
    language?: string;
}
export type FolderId = string;
export enum ScanType {
    receipt = "receipt",
    other = "other",
    card = "card",
    document_ = "document"
}
export enum UserPlan {
    premium = "premium",
    free = "free"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkUsageLimit(): Promise<UsageLimitsView>;
    createFolder(args: CreateFolderArgs): Promise<FolderView>;
    createOrUpdateSubscription(args: UpsertSubscriptionArgs): Promise<SubscriptionView>;
    createScan(args: CreateScanArgs): Promise<ScanView>;
    deleteAccount(): Promise<void>;
    deleteFolder(folderId: FolderId): Promise<void>;
    deleteScan(scanId: ScanId): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getOrCreateUser(): Promise<UserView>;
    getScan(scanId: ScanId): Promise<ScanView | null>;
    getSubscription(): Promise<SubscriptionView | null>;
    incrementScanCount(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listFolders(): Promise<Array<FolderView>>;
    listScans(args: ListScansArgs): Promise<ListScansResult>;
    resetDailyLimits(): Promise<void>;
    restoreScan(scanId: ScanId): Promise<void>;
    searchScans(searchQuery: string): Promise<Array<ScanView>>;
    updateScan(args: UpdateScanArgs): Promise<ScanView>;
    updateUser(args: UpdateUserArgs): Promise<UserView>;
}
import type { CreateScanArgs as _CreateScanArgs, ExternalBlob as _ExternalBlob, FolderId as _FolderId, ListScansArgs as _ListScansArgs, ListScansResult as _ListScansResult, ScanId as _ScanId, ScanType as _ScanType, ScanView as _ScanView, SubscriptionId as _SubscriptionId, SubscriptionView as _SubscriptionView, Timestamp as _Timestamp, UpdateScanArgs as _UpdateScanArgs, UpdateUserArgs as _UpdateUserArgs, UpsertSubscriptionArgs as _UpsertSubscriptionArgs, UserId as _UserId, UserPlan as _UserPlan, UserRole as _UserRole, UserView as _UserView, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkUsageLimit(): Promise<UsageLimitsView> {
        if (this.processError) {
            try {
                const result = await this.actor.checkUsageLimit();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkUsageLimit();
            return result;
        }
    }
    async createFolder(arg0: CreateFolderArgs): Promise<FolderView> {
        if (this.processError) {
            try {
                const result = await this.actor.createFolder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFolder(arg0);
            return result;
        }
    }
    async createOrUpdateSubscription(arg0: UpsertSubscriptionArgs): Promise<SubscriptionView> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateSubscription(to_candid_UpsertSubscriptionArgs_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SubscriptionView_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateSubscription(to_candid_UpsertSubscriptionArgs_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SubscriptionView_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async createScan(arg0: CreateScanArgs): Promise<ScanView> {
        if (this.processError) {
            try {
                const result = await this.actor.createScan(await to_candid_CreateScanArgs_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ScanView_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createScan(await to_candid_CreateScanArgs_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ScanView_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAccount(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAccount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAccount();
            return result;
        }
    }
    async deleteFolder(arg0: FolderId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFolder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFolder(arg0);
            return result;
        }
    }
    async deleteScan(arg0: ScanId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteScan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteScan(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrCreateUser(): Promise<UserView> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrCreateUser();
                return from_candid_UserView_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrCreateUser();
            return from_candid_UserView_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScan(arg0: ScanId): Promise<ScanView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getScan(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScan(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubscription(): Promise<SubscriptionView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscription();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscription();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementScanCount(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementScanCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementScanCount();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listFolders(): Promise<Array<FolderView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFolders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFolders();
            return result;
        }
    }
    async listScans(arg0: ListScansArgs): Promise<ListScansResult> {
        if (this.processError) {
            try {
                const result = await this.actor.listScans(to_candid_ListScansArgs_n35(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ListScansResult_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listScans(to_candid_ListScansArgs_n35(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ListScansResult_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetDailyLimits(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetDailyLimits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetDailyLimits();
            return result;
        }
    }
    async restoreScan(arg0: ScanId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreScan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreScan(arg0);
            return result;
        }
    }
    async searchScans(arg0: string): Promise<Array<ScanView>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchScans(arg0);
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchScans(arg0);
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateScan(arg0: UpdateScanArgs): Promise<ScanView> {
        if (this.processError) {
            try {
                const result = await this.actor.updateScan(to_candid_UpdateScanArgs_n40(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ScanView_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateScan(to_candid_UpdateScanArgs_n40(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ScanView_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUser(arg0: UpdateUserArgs): Promise<UserView> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(to_candid_UpdateUserArgs_n42(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserView_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(to_candid_UpdateUserArgs_n42(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserView_n29(this._uploadFile, this._downloadFile, result);
        }
    }
}
async function from_candid_ExternalBlob_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_ListScansResult_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListScansResult): Promise<ListScansResult> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_ScanType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScanType): ScanType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_ScanView_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScanView): Promise<ScanView> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionView_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionView): SubscriptionView {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserPlan_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPlan): UserPlan {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserView_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserView): UserView {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FolderId]): FolderId | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ScanView]): Promise<ScanView | null> {
    return value.length === 0 ? null : await from_candid_ScanView_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SubscriptionView]): SubscriptionView | null {
    return value.length === 0 ? null : from_candid_SubscriptionView_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SubscriptionId;
    stripeSubscriptionId: [] | [string];
    userId: _UserId;
    plan: string;
    currentPeriodEnd: [] | [_Timestamp];
}): {
    id: SubscriptionId;
    stripeSubscriptionId?: string;
    userId: UserId;
    plan: string;
    currentPeriodEnd?: Timestamp;
} {
    return {
        id: value.id,
        stripeSubscriptionId: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.stripeSubscriptionId)),
        userId: value.userId,
        plan: value.plan,
        currentPeriodEnd: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.currentPeriodEnd))
    };
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ScanId;
    isDeleted: boolean;
    scanType: _ScanType;
    userId: _UserId;
    createdAt: _Timestamp;
    tags: Array<string>;
    isFavorite: boolean;
    extractedText: string;
    confidenceScore: number;
    language: string;
    updatedAt: _Timestamp;
    image: _ExternalBlob;
    exportCount: bigint;
    folderId: [] | [_FolderId];
    isPinned: boolean;
}): Promise<{
    id: ScanId;
    isDeleted: boolean;
    scanType: ScanType;
    userId: UserId;
    createdAt: Timestamp;
    tags: Array<string>;
    isFavorite: boolean;
    extractedText: string;
    confidenceScore: number;
    language: string;
    updatedAt: Timestamp;
    image: ExternalBlob;
    exportCount: bigint;
    folderId?: FolderId;
    isPinned: boolean;
}> {
    return {
        id: value.id,
        isDeleted: value.isDeleted,
        scanType: from_candid_ScanType_n23(_uploadFile, _downloadFile, value.scanType),
        userId: value.userId,
        createdAt: value.createdAt,
        tags: value.tags,
        isFavorite: value.isFavorite,
        extractedText: value.extractedText,
        confidenceScore: value.confidenceScore,
        language: value.language,
        updatedAt: value.updatedAt,
        image: await from_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value.image),
        exportCount: value.exportCount,
        folderId: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.folderId)),
        isPinned: value.isPinned
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    scansToday: bigint;
    createdAt: _Timestamp;
    plan: _UserPlan;
    language: string;
    totalScans: bigint;
    updatedAt: _Timestamp;
}): {
    id: UserId;
    scansToday: bigint;
    createdAt: Timestamp;
    plan: UserPlan;
    language: string;
    totalScans: bigint;
    updatedAt: Timestamp;
} {
    return {
        id: value.id,
        scansToday: value.scansToday,
        createdAt: value.createdAt,
        plan: from_candid_UserPlan_n31(_uploadFile, _downloadFile, value.plan),
        language: value.language,
        totalScans: value.totalScans,
        updatedAt: value.updatedAt
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    scans: Array<_ScanView>;
}): Promise<{
    total: bigint;
    scans: Array<ScanView>;
}> {
    return {
        total: value.total,
        scans: await from_candid_vec_n39(_uploadFile, _downloadFile, value.scans)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    receipt: null;
} | {
    other: null;
} | {
    card: null;
} | {
    document: null;
}): ScanType {
    return "receipt" in value ? ScanType.receipt : "other" in value ? ScanType.other : "card" in value ? ScanType.card : "document" in value ? ScanType.document : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    premium: null;
} | {
    free: null;
}): UserPlan {
    return "premium" in value ? UserPlan.premium : "free" in value ? UserPlan.free : value;
}
async function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ScanView>): Promise<Array<ScanView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ScanView_n21(_uploadFile, _downloadFile, x)));
}
async function to_candid_CreateScanArgs_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateScanArgs): Promise<_CreateScanArgs> {
    return await to_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ListScansArgs_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListScansArgs): _ListScansArgs {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_ScanType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScanType): _ScanType {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateScanArgs_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateScanArgs): _UpdateScanArgs {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateUserArgs_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateUserArgs): _UpdateUserArgs {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_UpsertSubscriptionArgs_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpsertSubscriptionArgs): _UpsertSubscriptionArgs {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserPlan_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserPlan): _UserPlan {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stripeSubscriptionId?: string;
    plan: string;
    currentPeriodEnd?: Timestamp;
}): {
    stripeSubscriptionId: [] | [string];
    plan: string;
    currentPeriodEnd: [] | [_Timestamp];
} {
    return {
        stripeSubscriptionId: value.stripeSubscriptionId ? candid_some(value.stripeSubscriptionId) : candid_none(),
        plan: value.plan,
        currentPeriodEnd: value.currentPeriodEnd ? candid_some(value.currentPeriodEnd) : candid_none()
    };
}
async function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scanType: ScanType;
    tags: Array<string>;
    extractedText: string;
    confidenceScore: number;
    language: string;
    image: ExternalBlob;
    folderId?: FolderId;
}): Promise<{
    scanType: _ScanType;
    tags: Array<string>;
    extractedText: string;
    confidenceScore: number;
    language: string;
    image: _ExternalBlob;
    folderId: [] | [_FolderId];
}> {
    return {
        scanType: to_candid_ScanType_n18(_uploadFile, _downloadFile, value.scanType),
        tags: value.tags,
        extractedText: value.extractedText,
        confidenceScore: value.confidenceScore,
        language: value.language,
        image: await to_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value.image),
        folderId: value.folderId ? candid_some(value.folderId) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    includeDeleted: boolean;
    offset: bigint;
    limit: bigint;
    folderId?: FolderId;
}): {
    includeDeleted: boolean;
    offset: bigint;
    limit: bigint;
    folderId: [] | [_FolderId];
} {
    return {
        includeDeleted: value.includeDeleted,
        offset: value.offset,
        limit: value.limit,
        folderId: value.folderId ? candid_some(value.folderId) : candid_none()
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ScanId;
    tags?: Array<string>;
    isFavorite?: boolean;
    extractedText?: string;
    confidenceScore?: number;
    language?: string;
    exportCount?: bigint;
    folderId?: FolderId;
    isPinned?: boolean;
}): {
    id: _ScanId;
    tags: [] | [Array<string>];
    isFavorite: [] | [boolean];
    extractedText: [] | [string];
    confidenceScore: [] | [number];
    language: [] | [string];
    exportCount: [] | [bigint];
    folderId: [] | [_FolderId];
    isPinned: [] | [boolean];
} {
    return {
        id: value.id,
        tags: value.tags ? candid_some(value.tags) : candid_none(),
        isFavorite: value.isFavorite ? candid_some(value.isFavorite) : candid_none(),
        extractedText: value.extractedText ? candid_some(value.extractedText) : candid_none(),
        confidenceScore: value.confidenceScore ? candid_some(value.confidenceScore) : candid_none(),
        language: value.language ? candid_some(value.language) : candid_none(),
        exportCount: value.exportCount ? candid_some(value.exportCount) : candid_none(),
        folderId: value.folderId ? candid_some(value.folderId) : candid_none(),
        isPinned: value.isPinned ? candid_some(value.isPinned) : candid_none()
    };
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    plan?: UserPlan;
    language?: string;
}): {
    plan: [] | [_UserPlan];
    language: [] | [string];
} {
    return {
        plan: value.plan ? candid_some(to_candid_UserPlan_n44(_uploadFile, _downloadFile, value.plan)) : candid_none(),
        language: value.language ? candid_some(value.language) : candid_none()
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScanType): {
    receipt: null;
} | {
    other: null;
} | {
    card: null;
} | {
    document: null;
} {
    return value == ScanType.receipt ? {
        receipt: null
    } : value == ScanType.other ? {
        other: null
    } : value == ScanType.card ? {
        card: null
    } : value == ScanType.document ? {
        document_: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserPlan): {
    premium: null;
} | {
    free: null;
} {
    return value == UserPlan.premium ? {
        premium: null
    } : value == UserPlan.free ? {
        free: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
